### ISSUE TITLE
goto other tab

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_intext_bookmarks#4]
Длг показывает 3 таба
прыг в другой таб.
теперь фокус то на диалоге Пск то (нет поиска) на консоли.
надо делать ed.focus?

**Comment by kvichans** [comment]
не понял как это происходит
"прыг в др. таб" - это что?

**Comment by Alexey-T** [comment]
в 3 табах - букмарки.
они untitled. вызываю /Go to in tabs/ выбираю любой др.таб

**Comment by kvichans** [comment]
у меня нормально работает

**Comment by Alexey-T** [comment]
пробл. в Лине. =(
