### ISSUE TITLE
Rename opts

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_intext_bookmarks#6]
I found some txt, guess it is this code

  "ibm_signs": ["NOTE:", "NB!", "TODO:", "FIX:", "todo:", "todo."],

need not "ibm", ok prefix, eg "intextbookmk_"

**Comment by kvichans** [comment]
Todo

**Comment by kvichans** [comment]
Сделал синонимы: `intextbookmk_*` и `ibm_*`. Если есть оба, то приоритет у `ibm_*`

**Comment by Alexey-T** [comment]
Тогда запишется что, ibm_?

**Comment by kvichans** [comment]
"запишется"? Сейчас опции пишет только пользователь руками в user.json. Он может использовать любую форму ключей. Если случайно оставит синонимы, то будет взято значение от короткой формы

**Comment by Alexey-T** [comment]
Диалог опций пишет..

**Comment by kvichans** [comment]
Да, спасибо, есть такое. Пропустил это место. Будет писать только длинная форма ключей

**Comment by kvichans** [comment]
fix
